- hosts: localhost
  connection: ssh # or paramiko - https://groups.google.com/forum/#!topic/ansible-project/HqD9Z-29nV4
  vars:
    - node_version: 7 
    - is_ci: ansible_env.TRAVIS_JOB_ID is defined
    - isnt_ci: ansible_env.TRAVIS_JOB_ID is not defined
    - is_osx: ansible_os_family == 'Darwin'
    - is_ubuntu: ansible_distribution == 'Ubuntu'
    - is_ubuntu13_plus: is_ubuntu and ansible_distribution_version|int >= 13
    - is_ubuntu15_plus: is_ubuntu and ansible_distribution_version|int >= 15

  tasks:
    - include: tasks/template.yml

    # # essentials:
    # - include: tasks/apt.yml
    # - include: tasks/homebrew.yml
    # - include: tasks/core.yml
    # - include: tasks/dotfiles.yml


    # # specific stuff than can be commented out
    # # ----------------------------------------

    # # languages
    # - include: tasks/node.yml

    # # database server
    # - include: tasks/postgres.yml
    # - include: tasks/mariadb.yml

    # # database client
    # # - include: tasks/robomongo.yml
    # - include: tasks/sequel-pro.yml

    # # editors, IDEs, terminals, etc
    # - include: tasks/macdown.yml
    # # - include: tasks/sublime-text.yml
    # - include: tasks/terminal.yml
    # - include: tasks/visual-studio-code.yml

    # # tools
    # - include: tasks/chrome-devtools.yml
    # # - include: tasks/docker.yml
    # - include: tasks/hugo.yml
    # - include: tasks/ngrok.yml
    # - include: tasks/vpn.yml

    # # devops
    # - include: tasks/awscli.yml
    # - include: tasks/terraform.yml

    # # browsers
    # - include: tasks/chrome.yml

    # # backup
    # - include: tasks/droplr.yml
    # # - include: tasks/dropbox.yml
    # # - include: tasks/google-drive.yml

    # # chat
    # - include: tasks/screenhero.yml
    # - include: tasks/skype.yml
    # - include: tasks/slack.yml
    # - include: tasks/telegram.yml

    # # api
    # - include: tasks/insomnia.yml
    # - include: tasks/postman.yml

    # # images
    # - include: tasks/iconjar.yml

    # # media
    # - include: tasks/spotify.yml

    # # -----------------------------
    # # BREW CLEANUP
    # # -----------------------------
    # - name: Cleanup Homebrew & Cask
    #   command: brew cleanup && brew cask cleanup

    # # -----------------------------
    # # NPM MODULES
    # # -----------------------------

    # - include: tasks/npm.yml

    # # -----------------------------
    # # SYMLINKS (dotfiles)
    # # -----------------------------
    # - include: tasks/symlinks.yml

    # # -----------------------------
    # # REPOSITORIES
    # # -----------------------------
    # - include: tasks/repos.yml

    # # -----------------------------
    # # SETUP
    # # -----------------------------

    # - name: Setup git
    #   command: sh config/git/config.sh
    # - name: Setup vscode
    #   command: sh config/vscode/config.sh
    # - name: Setup macOS
    #   command: sh config/macos.sh
    # - name: Set zsh as default shell
    #   shell: chsh -s /bin/zsh
    #   when: isnt_ci
    #   become: false

    # # - name: Gets the zsh path
    # #   shell: which zsh
    # #   register: bin_zsh

    # # - name: Add homebrew zsh to /etc/shells
    # #   lineinfile: dest=/etc/shells line='{{ bin_zsh.stdout }}'
    # #   become: True

    # # - name: Set zsh as default shell
    # #   user: name=$user shell=/bin/zsh


    # # -----------------------------
    # # STARTUP
    # # -----------------------------

    # - name: Start services at login
    #   file: src=/usr/local/opt/{{ item }}/homebrew.mxcl.{{ item }}.plist path=~/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist state=link force=yes
    #   with_items: 
    #     - mariadb
    #   when: is_osx

    # - name: Setup launch agents for services
    #   command: launchctl load {{ home }}/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist
    #   with_items:
    #     - mariadb
    #   when: is_osx