# ansible-playbook sample.yml --flush-cache

- hosts: localhost
  # strategy: debug
  # connection: ssh # or paramiko - https://groups.google.com/forum/#!topic/ansible-project/HqD9Z-29nV4
  vars:
    - node_version: 7
    - is_ci: ansible_env.TRAVIS_JOB_ID is defined
    - isnt_ci: ansible_env.TRAVIS_JOB_ID is not defined
    - is_osx: ansible_os_family == 'Darwin'
    - is_ubuntu: ansible_distribution == 'Ubuntu'
    - is_ubuntu13_plus: is_ubuntu and ansible_distribution_version|int >= 13
    - is_ubuntu15_plus: is_ubuntu and ansible_distribution_version|int >= 15

  tasks:
    - name: New file OOO
      copy:
        content: ''
        dest: /Users/good/oooooo.txt
        force: yes
        mode: 0555

    # - name: New file UUU
    #   file:
    #     path: /Users/good/uuuuuuu.txt
    #     state: touch
    #     # owner: good
    #     # group: staff
    #     mode: 0555
    #     owner: root
    #     group: root
    #   ignore_errors: True
    #   changed_when: false

    # # -----------------------------
    # # STARTUP
    # # -----------------------------
    # - name: Start services at login
    #   file:
    #     src: /usr/local/opt/{{ item }}/homebrew.mxcl.{{ item }}.plist
    #     dest: ~/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist
    #     state: link
    #     force: yes
    #   with_items:
    #     - mariadb
    #   # when: is_osx

    # - name: Setup launch agents for services
    #   command: launchctl load ~/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist
    #   with_items:
    #     - mariadb
    #   when: is_osx
