- name: Install OSX-only core packages
  package: name={{ item }}
  with_items:
    - coreutils
    - dockutil
    - findutils
    - gawk
    - gnu-getopt
    - gnu-indent
    - gnu-sed
    - gnu-tar
    - gnutls
    - gpg
    - grc
    - pstree
    - unrar
    - watch

- name: Install core packages
  package: name={{ item }}
  with_items:
    - curl
    - fpp # https://facebook.github.io/PathPicker/

    # Editor
    - vim

    # Git
    - diff-so-fancy
    - git

    - htop
    - mcrypt
    - ncdu
    - openssl
    - tree
    - wget
    - yarn

    # Shell
    - tmux
    - zsh
    - zsh-completions

    # Languages
    - nodejs

    # Terraform
    - terraform

    # Ngrok
    - eqnxio/ngrok/ngrok

- name: Install Glances
  pip:
    name: glances
