- name: Install Ubuntu-only core packages
  package: name={{ item }}
  when: is_ubuntu
  with_items:
    - build-essential
    - openssh-server
    - smbclient
    - xsel

- name: Install ubuntu-restricted-extras
  package: name=ubuntu-restricted-extras
  when: is_ubuntu

- name: Install OSX-only core packages
  package: name={{ item }}
  when: is_osx
  with_items:
    - coreutils
    - findutils
    - gawk
    - gnu-getopt
    - gnu-indent
    - gnu-sed
    - gnu-tar
    - gnutls
    - gpg
    - grc
    - pstree
    - unrar
    - watch

- name: Install core packages
  package: name={{ item }}
  with_items:
    - curl
    - diff-so-fancy
    - fpp # https://facebook.github.io/PathPicker/
    - git
    - htop
    - mcrypt
    - ncdu
    - openssl
    - tmux
    - tree
    - vim
    - wget
    - yarn
    - zsh
    - zsh-completions
