- name: Install Dropbox
  apt: deb=https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb
  when: is_ubuntu

- name: Install Dropbox
  homebrew_cask: name=dropbox
  when: is_osx