- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Add Homebrew taps
  homebrew_tap:
    tap: "{{ item }}"
  with_items: >
    {{ homebrew_taps }}

- name: Install Homebrew casks
  homebrew_cask:
    name: "{{ item }}"
  with_items: >
    {{ homebrew_cask_apps }}

- name: Install Homebrew packages
  homebrew:
    name: "{{ item }}"
  with_items: >
    {{ homebrew_packages }}

- name: Cleanup Homebrew & Cask
  shell: brew cleanup && brew cask cleanup
