- name: Install MariaDB Server
  homebrew:
    name: mariadb

# - name: Install MariaDB database
#   shell: mysql_install_db
#   ignore_errors: yes

- name: Configure MariaDB
  template:
    src: my.cnf.j2
    dest: /usr/local/etc/my.cnf
    mode: 0644


