- name: Cloning repos + submodules
  git: repo=git@gitlab.com:cleanify/{{ item.repo }}.git
       dest=~/git/{{ item.dest }}
       accept_hostkey=yes
       force=yes
       recursive=no
       key_file=~/.ssh/cleanify-shiny.pem
       # key_file=/home/user/.ssh/id_rsa.github-{{ item.repo }}
  with_items:
    -
      repo: meta
      dest: 'meta'
      
    # -
    #   dest: "{{ destination }}/app/core"
    #   repo: SubmoduleRepo



# - name: Create the SSH public key file
#   copy: content="{{ git_ssh_pub_key }}"
#         dest=/root/.ssh/id_rsa.pub
#         mode=0644

# - name: Create the SSH private key file
#   copy: content="{{ git_ssh_priv_key }}"
#         dest=/root/.ssh/id_rsa
#         mode=0600