- name: Create ~/.ssh folder
  file:
    path: ~/.ssh
    state: directory
    mode: 0755

- name: Collect ~/.ssh files
  find:
    paths: "~/.ssh/"
    hidden: false
    recurse: true
  register: collected_files

- name: Chmod 0400 to files on ~/.ssh/
  file:
    path: "{{ item.path }}"
    state: file
    owner: "{{ user }}"
    mode: 0400
  with_items: >
    {{
      collected_files.files
    }}

- name: Chmod 0600 to ~/.ssh/config
  file:
    path: ~/.ssh/config
    state: file
    mode: 0600

- name: Add ssh key id_rsa
  shell: ssh-add -K ~/.ssh/id_rsa
