#!/bin/zsh

# Hide the “user@hostname” info when you’re
# logged in as yourself on your local machine
export DEFAULT_USER=`whoami`

export ZSH="$HOME/.oh-my-zsh"

# Shortcut to this dotfiles path is $DOTFILES
export DOTFILES="$HOME/dotfiles"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='code'
else
   # export EDITOR='mvim -f'
   export EDITOR='code'
fi
export VISUAL=$EDITOR
export USE_EDITOR=$EDITOR

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Import all of our zsh files
typeset -U config_files
config_files=($DOTFILES/*/*/*.zsh)

# Load the path files
for file in ${(M)config_files:#*/path.zsh}; do
  source "$file"
done
unset file;

# Put the bin/ directories first on the path
export PATH=$DOTFILES/bin:$DOTFILES/local/bin:$PATH

# Load everything but the path and completion files
for file in ${${config_files:#*/path.zsh}:#*/completion.zsh}; do
  source "$file"
done

# Load antibody plugins
# source ~/.zsh_plugins.sh

source $ZSH/oh-my-zsh.sh

# Initialize autocomplete here, otherwise functions won't be loaded
autoload -Uz compinit
typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
  compinit -i
else
  compinit -C -i
fi

# load every completion after autocomplete loads
for file in ${(M)config_files:#*/completion.zsh}; do
  source "$file"
done
unset file;

unset config_files updated_at

# use .localrc for SUPER SECRET CRAP that you don't
# want in your public, versioned repo.
# shellcheck disable=SC1090
[ -f ~/.localrc ] && . ~/.localrc

# # Use .localrc for things that need to be kept secret
# if [[ -a ~/.localrc ]]
# then
#   source ~/.localrc
# fi

# Make sure DEFAULT_USER has been set
if [ -z "$DEFAULT_USER" ]; then
  echo "Please set DEFAULT_USER in your ~/.localrc"
  exit 1
fi

# Node Version Manager
export NVM_DIR="${HOME}/.nvm"

# Enable persistent REPL history for `node`.
export NODE_REPL_HISTORY=~/.node_history;

# Allow 32³ entries; the default is 1000.
export NODE_REPL_HISTORY_SIZE='32768';

# Use sloppy mode by default, matching web browsers.
export NODE_REPL_MODE='sloppy';

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# vi mode
# This function changes the cursor depending on if in normal or insert mode
function zle-keymap-select zle-line-init
{
    # change cursor shape in iTerm2
    case $KEYMAP in
        vicmd)      print -n -- "\E]50;CursorShape=0\C-G";;  # block cursor
        viins|main) print -n -- "\E]50;CursorShape=1\C-G";;  # line cursor
    esac

    zle reset-prompt
    zle -R
}

function zle-line-finish
{
    print -n -- "\E]50;CursorShape=0\C-G"  # block cursor
}

zle -N zle-line-init
zle -N zle-line-finish
zle -N zle-keymap-select

bindkey -v    # enable vi mode
bindkey '^R' history-incremental-pattern-search-backward  # enable ctrl+R history search, must come after bindkey -v

# ---------------------------------------------------------
# CUSTOMIZATION
# ---------------------------------------------------------
# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="kafeitu"
# ZSH_THEME="agnoster"
# ZSH_THEME="wezm"
ZSH_THEME="amuse"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# don't nice background tasks
NO_BG_NICE="true"
NO_HUP="true"
NO_LIST_BEEP="true"
# allow functions to have local options
LOCAL_OPTIONS="true"
# allow functions to have local traps
LOCAL_TRAPS="true"
# share history between sessions ???
SHARE_HISTORY="true"
# add timestamps to history
EXTENDED_HISTORY="true"
PROMPT_SUBST="true"
CORRECT="true"
COMPLETE_IN_WORD="true"
# adds history
APPEND_HISTORY="true"
# adds history incrementally and share it across sessions
INC_APPEND_HISTORY="true"
SHARE_HISTORY="true"
# don't record dupes in history
HIST_IGNORE_ALL_DUPS="true"
HIST_REDUCE_BLANKS="true"
HIST_IGNORE_DUPS="true"
HIST_IGNORE_SPACE="true"
HIST_VERIFY="true"
HIST_EXPIRE_DUPS_FIRST="true"
# If you do a 'rm *', Zsh will give you a sanity check!
RM_STAR_WAIT="true"

autoload -U promptinit; promptinit
prompt pure

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh
