- hosts: localhost
  strategy: debug
  connection: local # ssh or paramiko - https://groups.google.com/forum/#!topic/ansible-project/HqD9Z-29nV4
  vars:
    - node_version: 7
    - user: "{{ lookup('env','USER') }}"
    - is_ci: ansible_env.TRAVIS_JOB_ID is defined
    - isnt_ci: ansible_env.TRAVIS_JOB_ID is not defined
    - is_osx: ansible_os_family == 'Darwin'
    - is_ubuntu: ansible_distribution == 'Ubuntu'
    - is_ubuntu13_plus: is_ubuntu and ansible_distribution_version|int >= 13
    - is_ubuntu15_plus: is_ubuntu and ansible_distribution_version|int >= 15

  vars_files:
    - vars/main.yml

  tasks:
    - include: tasks/applications.yml
    # - include: tasks/dock.yml

    # # essentials:
    # - include: tasks/ssh.yml
    # - include: tasks/apt.yml
    # - include: tasks/homebrew.yml
    # - include: tasks/core.yml
    # - include: tasks/dotfiles.yml


    # # specific stuff than can be commented out
    # # ---------------------------------------
    # # database server
    # - include: tasks/postgres.yml
    # # - include: tasks/mariadb.yml

    # # tools
    # - include: tasks/chrome-devtools.yml
    # # - include: tasks/docker.yml
    # - include: tasks/hugo.yml
    # - include: tasks/ngrok.yml
    # - include: tasks/vpn.yml

    # # devops
    # - include: tasks/awscli.yml
    # - include: tasks/terraform.yml

    # # -----------------------------
    # # BREW CLEANUP
    # # -----------------------------
    # - name: Cleanup Homebrew & Cask
    #   shell: brew cleanup && brew cask cleanup

    # # -----------------------------
    # # NPM MODULES
    # # -----------------------------
    # - include: tasks/npm.yml

    # # -----------------------------
    # # REPOSITORIES
    # # -----------------------------
    # - include: tasks/repos.yml

    # # -----------------------------
    # # SETUP
    # # -----------------------------
    # - name: Setup git
    #   shell: config/git/config.sh

    # - name: Setup vscode
    #   shell: config/vscode/config.sh

    # - name: Set zsh as default shell
    #   user:
    #     name: "{{ user }}"
    #     shell: /bin/zsh
    #   when: isnt_ci
    #   become: false

    # # -----------------------------
    # # STARTUP
    # # -----------------------------
    # - name: Start services at login
    #   file:
    #     src: /usr/local/opt/{{ item }}/homebrew.mxcl.{{ item }}.plist
    #     dest: ~/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist
    #     state: link
    #     force: yes
    #   with_items:
    #     - mariadb
    #   when: is_osx

    # - name: Setup launch agents for services
    #   command: launchctl load ~/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist
    #   with_items:
    #     - mariadb
    #   when: is_osx

    # # -----------------------------
    # # SECURITY
    # # -----------------------------
    # - include: tasks/mariadb-secure.yml

    # # -----------------------------
    # # DEFAULTS
    # # -----------------------------
    # # - name: Use macosx defaults
    # #   shell: config/macosx.sh
