- name: Install MariaDB repository
  apt_repository: repo='deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/ubuntu trusty main' state=present
  when: is_ubuntu

- name: Add repository key to the system
  apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db
  when: is_ubuntu

- name: Install MariaDB Server
  apt: name=mariadb-server state=latest update_cache=yes
  when: is_ubuntu

- name: Configure MariaDB
  template:
    src: my.cnf.j2
    dest: /etc/mysql/conf.d/my.cnf
    mode: 0644
  notify: restart mysql
  when: is_ubuntu
