- name: MongoDB | Add repository
  apt_repository:
    filename: '/etc/apt/sources.list.d/mongodb-org-3.2.list'
    repo: 'deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse'
    state: present
    update_cache: yes
  when: is_ubuntu

- name: MongoDB | Install MongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
  when: is_ubuntu

- name: MongoDB | Ensure that MongoDB is running
  service:
    name: mongod
    state: started
  when: is_ubuntu